# Generated by Django 5.2.6 on 2025-09-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bug_type', models.CharField(choices=[('gameplay_or_mechanics', 'Gameplay & Mechanics'), ('graphics_or_performance', 'Graphics & Performance'), (' network_or_multiplayer', ' Network & Multiplayer'), ('ui_or_game_logic', 'UI & Game Logic'), ('other', 'Other(Explain in Description)')])),
                ('description', models.TextField()),
                ('number_of_occurences', models.IntegerField()),
            ],
        ),
    ]
