# Generated by Django 5.2.6 on 2025-09-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='name',
        ),
    ]
